server:
    port: 8081
spring:
    data:
        mongodb:
            uri: 'mongodb://localhost:27017/Bookstore'
            database: Bookstore
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: 'http://localhost:8080/realms/SpringBooksRealm'
                    jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
springdoc:
  swagger-ui:
    oauth:
      client-id: spring-app